global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus_master
    scrape_interval: 5s
    static_configs:
      - targets: [sdsdf:9090]
  - job_name: node_exporter_rocky
    scrape_interval: 5s
    static_configs:
      - targets: [sdsdf:9100]
  - job_name: hbase
    scrape_interval: 5s
    static_configs:
      - targets: [sdsdf:8090]
  - job_name: namenode
    scrape_interval: 5s
    static_configs:
      - targets: [sdsdf:27001]
  - job_name: datanodes
    scrape_interval: 5s
    static_configs:
      - targets: [sdsdf:27002]
